language: ruby
rvm:
  - 2.3.0-p0
script: rspec spec
task :default => [:spec]
desc 'run Rspec specs'
task :spec do
  sh 'rspec spec'
end
/home/travis/build/mscherer11/i-shop-beer/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `rescue in connect': FATAL:  database "i-shop-beer_test" does not exist (ActiveRecord::NoDatabaseError)
